Fallback (temporarily) to Gradle 2.14.1
Due to incompatibility between Gradle 2 and 3.
Caused by: java.lang.NoSuchMethodError: org.gradle.api.tasks.TaskOutputs.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskOutputFilePropertyBuilder;
    at org.shipkit.internal.gradle.notes.ReleaseNotesPlugin$2.execute(ReleaseNotesPlugin.java:83)